services:
  postgres:
    image: postgres:15-alpine
    container_name: meu-postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: senhasegura
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network
  
  elastichsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    ports:
      - "9200:9200"
    container_name: meu-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - dev-network
    volumes:
      - scaffoldapp:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: meu-kibana
    ports:
      - "5601:5601"
    depends_on:
      - elastichsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - dev-network

volumes:
  postgres-data:
  scaffoldapp:

networks:
  dev-network:
    driver: bridge