services:
  postgres:
    image: postgres:15-alpine
    container_name: meu-postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: senhasegura
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network

volumes:
  postgres-data:

networks:
  dev-network:
    driver: bridge